# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Occasionally interesting thoughts
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about computers, mathematics, and philosophy. Occasionally,
  other people find my thoughts on these topics interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samgrayson.me" # the base hostname & protocol for your site
twitter_username: 
github_username:  charmoniumQ
language: en_US
favicon_img: true
favicon_img_path: /favicon.ico

# Build settings
markdown: kramdown

gems:
  - jekyll-archives
